### ISSUE TITLE
Fix: bullet in Name

### ISSUE THREAD

**Issue by KukretiShubham** [cac-nitj/pr-practice#26]
![image](https://user-images.githubusercontent.com/57281769/134136642-016532be-0a05-4e7c-acf0-f6dbb436ae53.png)
Fix bullet in the name

**Comment by Kajal13081** [comment]
> ![image](https://user-images.githubusercontent.com/57281769/134136642-016532be-0a05-4e7c-acf0-f6dbb436ae53.png)
> Fix bullet in the name

#28 
issue fixed
